- name: variabls from inventory
  hosts: localhost
  connection: local
  tasks:
    - name: print course info
      ansible.builtin.debug:
        msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"


# ansible-playbook -i inventory.ini 11-vars-args.yaml -e "COURSE=ARGS" -e "DURATION=10MIN" -e "TRAINER=SIVAKUMAR_REDDY"        