- name: understand vars preference
  hosts: localhost
  connection: local
   vars:
     GREETING: "Hello form PLAY"
   vars_files:
     - course.yaml
   vars_prompt:
     - name: GREETING
       prompt: please enter the greeting
       private: false
  tasks: 
    - name: print the greeting    
       vars:
         GREETING: "Hello from TASK"
      ansible.builtin.debug:
        msg: "{{ GREETING }}"  


# 1. command line or args
# 2. task
# 3. file
# 4. prompt
# 5. play level
# 6. inventory
      