- name: install packages 
  hosts: localhost
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.debug:
      name: "{{ items }}"
      state: installed
    loop:
    - mysql  
    - nginx
    - zip
    - Python3
