- name: install packages 
  hosts: frontend
  became: yes
  tasks:
  - name: install packages
    ansible.builtin.packages:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql  
    - nginx
    - zip
    - Python3
