- name: function
  hosts: localhost
  connection: local
  vars:
    persons: "Ramesh,Ram,Sam,Lakshmi"
  tasks:
    - name: check undefined variable
      ansible.builtin.debug:
        msg: "Hello, {{ person | default('Ramesh') }}"


    - name: print names
      ansible.builtin.debug:
        msg: "Hello, {{ persons | split(',') }}"

    - name: convert map into list
      vars:
        course:
          name: ansible
          duration: 10HR
          trainer: Sivakumar
      ansible.builtin.debug:
        msg:  "Course Info: {{ course | dict2items }}"      


    - name: convert list into map
      vars:
        course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10HR'}
        - {'key': 'trainer', 'value': 'Sivakumar'}  
      ansible.builtin.debug:
        msg:  "Course Info: {{ course | items2dict }}"    

    - name: convert to uppercase
      vars:
        name: "lakshminarasimha p k"
      ansible.buildin.debug:
        msg: "Hello {{ name | upper }}"  
