- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    subnet_id: subnet-09a4b8c039b4eb497 
    sg_id: sg-032739b3c91414e33 
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"  
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instance }}"  