- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    subnet_id: subnet-09a4b8c039b4eb497 
    sg_id: sg-032739b3c91414e33 
    zone: lakshmi.cyou
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"    
      record: "{{ item.time}}.{{ zone }}"
      type: A
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }}"  