- name: PLAY1
  hosta: local
  connection: local
  tasks:
  - name: hello from play 1 and tasks1
    ansible.builtin.debug:
      msg: "Hello from PLAY-1 and TASK-1"

  - name: hello from play 1 and tasks2
    ansible.builtin.debug:
      msg: "Hello from PLAY-1 and TASK-2"    

- name: PLAY2
  hosta: local
  connection: local
  tasks:
  - name: hello from play 2 and tasks1
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 and TASK-1"

  - name: hello from play 2 and tasks2
    ansible.builtin.debug:
      msg: "Hello from PLAY-2 and TASK-2"          