- name: play level variables
  hosts: localhost
  connection: local
  vars: 
    COURSE: Ansible #in equal to COURCE=Ansible in shell, shell we refer $VAR or (VAR)
    DURATION: 10HR
    TRAINER: Sivakumar Reddy
  tasks: 
    - name: print course imformation 
      ansible.builtin.debug:
    #vars reference should be surrounded by ""
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"  

    - name: print course imformation 
      ansible.builtin.debug:
    #vars reference should be surrounded by ""
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"  

