- name: play level variables
  hosts: localhost
  connection: local
  vars: 
    COURSE: DevOps with AWS 
    DURATION: 10HR
    TRAINER: sivakumar Reddy
  tasks: 
    - name: print course imformation 
      vars:
        COURSE: Ansible
      ansible.builtin.debug:
    #vars reference should be surrounded by ""
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"  


    - name: print course imformation 
      ansible.builtin.debug:
    #vars reference should be surrounded by ""
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"    

    

