- name: variabls from prompt
  hosts: localhost
  connection: local
  tasks:
    - name: print course info
      ansible.builtin.debug:
        msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"